pub mod agent;
pub mod ai;
pub mod ai_bridge;
pub mod animation;
pub mod audio;
pub mod chat_overlay;
pub mod chat_ui;
pub mod per_pet_window;
pub mod settings_ui;
pub mod config;
pub mod creature;
pub mod error;
pub mod ipc;
pub mod platform;
pub mod providers;
pub mod rag;
pub mod render;
pub mod scheduler;
pub mod hardware;
pub mod screen_physics;
pub mod state;
pub mod system_tray;
pub mod system_integration;
pub mod tts;

pub use agent::{AgentRuntime, AgentConfig, Tool, AgentEvent, default_tools};
pub use ai::{AiEngine, AiRequest, AiResponse, AiConfig, Message, MessageRole};
pub use ai_bridge::AiChatBridge;
pub use audio::{AudioSystem, AudioConfig, AudioEvent, SoundCategory};
pub use chat_overlay::{ChatOverlay, ChatOverlayEvent, ChatMessage, MessageRole as ChatMsgRole};
pub use config::{ConfigManager, ScreenBuddyConfig, Theme};
pub use creature::{Creature, load_creature_from_file};
pub use error::{Error, Result};
pub use render::renderer::Renderer;
pub use screen_physics::{CreaturePhysics, CreaturePersonality, ScreenManager, Monitor};
pub use scheduler::{ThreadPool, TaskPriority};
pub use hardware::{HardwareProfile, CpuInfo, GpuInfo, hardware_profile};
pub use state::{AppState, AppConfig, State, CreatureStateMachine};
pub use system_tray::{SystemTray, TrayEvent};
pub use system_integration::{SystemEvent, SystemEventType, SystemIntegration, SystemMonitor};
pub use tts::{TtsConfig, TtsEngine, TtsSystem};
pub use per_pet_window::{PerPetWindowManager, PetWindowConfig, PetWindowEvent, PetWindowId};
pub use rag::RagPipeline;
pub use settings_ui::{SettingsCategory, SettingsUI, SettingValue};
